#!/bin/bash

#########################
#    build super.img    #
#########################

sfx0="img"
sfx1="PARTITION"
sfx2="raw"
attr="readonly"
overhead="4194304"

SUPER_IMAGE="$(realpath "../$9$2.$sfx1.$sfx2")"
PLATFORM_TOOLS="$(readlink -f platform_tools)"

if [[ ! -f "$SUPER_IMAGE" ]]; then
    echo -e "\033[1m\033[33mplease cleanup build and run <make mod-unpack-""$2"">\033[0m"
    exit 2
fi

if [[ -e "$1/$2.$sfx0" ]]; then
    printf "\n%s\n" "remove old $2.$sfx0"
    find "$1"/ -name "$2*" -exec rm -f {} +
fi

# Get super.img info
metadata_size="$("$PLATFORM_TOOLS"/lpdump ../"$9""$2"."$sfx1"."$sfx2" | grep "Metadata max size:" | awk '{print $4}')"
printf "\n" "Metadata max size: %d\n" "$metadata_size"

slot_count="$("$PLATFORM_TOOLS"/lpdump ../"$9""$2"."$sfx1"."$sfx2" | grep "Metadata slot count:" | awk '{print $4}')"
printf "Metadata slot count: %d\n" "$slot_count"

group_name="$("$PLATFORM_TOOLS"/lpdump ../"$9""$2"."$sfx1"."$sfx2" | grep "Group:" | awk '{print $NF}' | sed '1!d')"
group_size="$("$PLATFORM_TOOLS"/lpdump ../"$9""$2"."$sfx1"."$sfx2" | grep "Maximum size:" | awk '{print $3}' | sed '1d')"
printf "Group name: %s\n" "$group_name"

device_size="$(fdtget -t u part_table /partitions/"$2" size | sed 's/0 //')"
printf "Device $2 size: %d\n" "$device_size"

group_size="$(( device_size - overhead ))"
printf "Overhead: %d\n" "$overhead"
printf "Group maximum size: %d\n" "$group_size"

# Get sum of partitions
cd "$1" || exit

sum=0
while read -r n; do
    sum="$(( sum + n ))"
done < <(stat -c %s -- *.$sfx0)

if [ "$sum" -ne '0' ]; then
    printf "Sum of partition sizes: %d\n" "$sum"
fi

# Build super.img
if [[ "$sum" -le "$group_size" ]]; then
    "$PLATFORM_TOOLS"/lpmake \
    --metadata-size="$metadata_size" \
    --super-name="$2" \
    --metadata-slots="$slot_count" \
    --device-size="$device_size" \
    --group="$group_name":"$group_size" \
    --partition="$3":"$attr":"$(stat -c %s "$3"."$sfx0")":"$group_name" \
    --partition="$4":"$attr":"$(stat -c %s "$4"."$sfx0")":"$group_name" \
    --partition="$5":"$attr":"$(stat -c %s "$5"."$sfx0")":"$group_name" \
    --partition="$6":"$attr":"$(stat -c %s "$6"."$sfx0")":"$group_name" \
    --partition="$7":"$attr":"$(stat -c %s "$7"."$sfx0")":"$group_name" \
    --partition="$8":"$attr":"$(stat -c %s "$8"."$sfx0")":"$group_name" \
    --image="$3"="$3"."$sfx0" \
    --image="$4"="$4"."$sfx0" \
    --image="$5"="$5"."$sfx0" \
    --image="$6"="$6"."$sfx0" \
    --image="$7"="$7"."$sfx0" \
    --image="$8"="$8"."$sfx0" \
    --sparse \
    --output="$2"."$sfx0" &>/dev/null
else
    echo -e "\n\033[1m\033[33mplease apply <mod-resize-super>\033[0m"
    exit 2
fi

